substitutions:
  _IMAGE: 'sheet-updater-image'
  _JOB_NAME: 'sheet-updater-job'
  _REGION: 'asia-northeast1'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE', 'sheet_updater']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - '$_JOB_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/$_IMAGE'
  - '--region'
  - '$_REGION'
  - '--execute-now'
images:
- gcr.io/$PROJECT_ID/$_IMAGE
options:
  logging: 'CLOUD_LOGGING_ONLY'
