substitutions:
  _JOB_NAME: 'sheet-updater-job'
  _REGION: 'asia-northeast1'
  _IMAGE_NAME: 'sheet-updater-image'
steps:
# 1. Dockerfileを使ってコンテナイメージをビルドする
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME', '.']

# 2. ビルドしたイメージをGCRにプッシュし、このステップにIDを付ける
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push to GCR'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME']

# 3. 直前のステップでプッシュした、特定のイメージを使ってデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - '$_JOB_NAME'
  - '--image'
  - '$(steps.[Push to GCR].images[0])' # ここで特定のイメージを指定
  - '--region'
  - '$_REGION'
  - '--set-secrets=/app/service_account.json=sheet-updater-key:latest'
  - '--execute-now'
options:
  logging: CLOUD_LOGGING_ONLY