steps:
# 1. コンテナイメージをビルドし、「:latest」というタグを付ける
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/moriya365/sheet-updater-image:latest', '.']

# 2. 「:latest」タグが付いたイメージをプッシュする
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/moriya365/sheet-updater-image:latest']

# 3. 「:latest」タグが付いたイメージを、具体的な名前でジョブにデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - 'sheet-updater-job'
  - '--image'
  - 'gcr.io/moriya365/sheet-updater-image:latest'
  - '--region'
  - 'asia-northeast1'
  - '--set-secrets=/app/service_account.json=sheet-updater-key:latest'
  - '--execute-now'
options:
  logging: CLOUD_LOGGING_ONLY